### ISSUE TITLE
Non ascii chars might be lost after formatting

### ISSUE THREAD

**Issue by bcardiff** [crystal-lang-tools/vscode-crystal-lang#114]
Even if the formatter returns no changes.

One of the examples I have is in https://github.com/crystal-lang/crystal/blob/b977a952e142efe5ee63e65e7820eec2b55a0c07/spec/std/io/io_spec.cr#L622

Extension version 0.4.0

```
$ crystal --version
Crystal 0.34.0 (2020-04-07)

LLVM: 10.0.0
Default target: x86_64-apple-macosx
```

How does it looks?

![CMIgznz7l7](https://user-images.githubusercontent.com/459923/81943639-0521e680-95d2-11ea-97d4-aed2e215b348.gif)

**Comment by pyritewolf** [comment]
For more context, this happens when **Format on Save** is enabled in VSCode's user configs, even if the plugin's features are all disabled
<img width="777" alt="Screen Shot 2020-07-28 at 14 09 44" src="https://user-images.githubusercontent.com/11891611/88698116-ff6d7480-d0db-11ea-8f10-a62b36d41487.png">

**Comment by maxbertinetti** [comment]
On version 0.6.2 is not happen anymore.

I close the issue.

![image](https://user-images.githubusercontent.com/26814295/99870703-8ab3ce00-2bd5-11eb-890c-f9dd7fd41fac.png)
(Afer Save with Format on Save enabled)
