### ISSUE TITLE
Adding extension to VSCodium

### ISSUE THREAD

**Issue by ilhamdev0** [crystal-lang-tools/vscode-crystal-lang#120]
When using VSCodium (fork of VSCode) unfortunately I couldn't find this extension in their marketplace so there is no support for crystal lang. is there a plan adding to their marketplace too? That would be great.

**Comment by pyritewolf** [comment]
Some more information I gathered with my coworkers: in VSCodium 1.45 the extension was visible, but in later versions (last we tried, 1.47.2) was not available. I think something changed as to what VSCode extensions are displayed on the VSCodium extension browser. It would be cool for the plugin to be displayed!

fwiw the extension itself can still be downloaded from the VSCode marketplace and installed on VSCodium, so that's a viable workaround 🙂

**Comment by ilhamdev0** [comment]
thank u :+1:
