### ISSUE TITLE
Color change when adding return type to class method

### ISSUE THREAD

**Issue by jwoertink** [crystal-lang-tools/vscode-crystal-lang#157]
Notice in this screenshot, the methods being called in the `run` instance method are currently white, and the class `self.run` method has no return type

![image](https://user-images.githubusercontent.com/2391/211863663-9c268d7e-0952-456e-b09c-67c505ef33c5.png)

Then when I add a return type to the class `self.run` method, all of the calls in the instance run method turn blue

![image](https://user-images.githubusercontent.com/2391/211863836-79aba68b-0c7c-4772-8cbc-0c2475ded990.png)

**Comment by nobodywasishere** [comment]
I wasn't able to replicate this for some reason. What theme are you using in VSCode?

![Screenshot_2023-07-21_00-05-45](https://github.com/crystal-lang-tools/vscode-crystal-lang/assets/32797552/a581654b-bc04-4cbb-a18b-d2c062c37cb6)
![Screenshot_2023-07-21_00-05-58](https://github.com/crystal-lang-tools/vscode-crystal-lang/assets/32797552/281f5d3a-3a4c-4d78-af2d-b20f5402f212)

**Comment by jwoertink** [comment]
I've switched themes, and I'm still getting this. Here's some more info:

![image](https://github.com/crystal-lang-tools/vscode-crystal-lang/assets/2391/4b06d8e8-9b22-4ea7-afd3-38a83a50fcfd)

The theme I'm using now is "Bearded Theme Black and Emerald".

The specific file in the screenshots is actually from Lucky 

https://github.com/luckyframework/lucky_cli/blob/main/src/generators/web.cr

another interesting issue here is that if I create a different class method, this doesn't happen... seems to be just that one?

![image](https://github.com/crystal-lang-tools/vscode-crystal-lang/assets/2391/0110d5fe-cb6a-44d1-952b-aaf18b2f51c0)
![image](https://github.com/crystal-lang-tools/vscode-crystal-lang/assets/2391/5227aeca-bf0d-43e8-9f22-300cf180ecf4)

Very strange :joy:

**Comment by nobodywasishere** [comment]
Ah thank you! I figured it out. The `end` condition for methods with arguments didn't account for return parameters, and so it was capturing everything afterwards. https://github.com/crystal-lang-tools/vscode-crystal-lang/blob/c990acde25a020e910ca1092991e62289ceaa6c9/syntaxes/crystal.json#L291C6-L291C6. With a small change this should be fixed in the next release!

![Screenshot_2023-07-22_17-54-56](https://github.com/crystal-lang-tools/vscode-crystal-lang/assets/32797552/d9b93af9-c300-44c8-9b66-de6e29ea8638)
![Screenshot_2023-07-22_17-54-15](https://github.com/crystal-lang-tools/vscode-crystal-lang/assets/32797552/34fe0caa-167c-4e80-ba82-5b274f451bbf)

**Comment by jwoertink** [comment]
Woo hoo! Good find :+1:

**Comment by jwoertink** [comment]
This looks to be fixed in the v0.9.0-alpha release.
