### ISSUE TITLE
Keep getting "Crystal compiler not found. spawn crystal ENOENT" errors.

### ISSUE THREAD

**Issue by DeepSpace2** [crystal-lang-tools/vscode-crystal-lang#19]
Hi. I have Bash on Windows, Crystal and https://github.com/faustinoaq/crystal-windows-installer installed.

My relevant VSCode settings are

```json
{
    "crystal-lang.hover": true,
    "crystal-lang.implementations": true,
    "crystal-lang.completion": true,
    "crystal-lang.bashOnWindows": true
}
```

Everything seems to work as expected however I keep getting `Crystal compiler not found. spawn crystal ENOENT` errors. Is there another setting hiding somewhere that needs to be tweaked?

**Comment by faustinoaq** [comment]
Hi @DeepSpace2 

I found the problem, Seems that Node.js backend is not detecting `c:\> crystal` but `c:\>crystal.bat`

So, you need to add `"crystal-lang.compiler": "crystal.bat"` to the settings:

```json
{
    "crystal-lang.hover": true,
    "crystal-lang.implementations": true,
    "crystal-lang.completion": true,
    "crystal-lang.bashOnWindows": true,
    "crystal-lang.compiler": "crystal.bat"
}
```

I could fix this issue by using a `crystal.exe` instead of `crystal.bat` but then antivirus are the problem.

**Comment by faustinoaq** [comment]
I added an wiki entry about this :point_down: 

https://github.com/crystal-lang-tools/vscode-crystal-lang/wiki/Settings#bashonwindows

**Comment by DeepSpace2** [comment]
Awesome! thanks :)
