### ISSUE TITLE
Code Formatting behave strangely

### ISSUE THREAD

**Issue by iambudi** [crystal-lang-tools/vscode-crystal-lang#80]
After upgrading crystal language to 0.27.1 and 0.27.2, code formatting replace all the entire code in a file with `"Error: Invalid option: -f"`.

**Comment by faustinoaq** [comment]
Oh, I just realize crystal has removed some flags :sweat_smile:

**Comment by faustinoaq** [comment]
Hi new version here https://github.com/crystal-lang-tools/vscode-crystal-lang/releases/tag/v0.3.11 (includes quickfix for this issue :wink: )

**Comment by ndbroadbent** [comment]
Hello, this issue is still happening for me, so I was wondering if this issue could please be re-opened? 

I am using "format on save", and when my code has an error, crystal replaces the source code in the file with the error message. E.g.

```
syntax error in 'STDIN:1:49': expecting any of these tokens: IDENT, CONST, +, -, *, /, //, %, |, &, ^, ~, **, <<, <, <=, ==, !=, =~, !~, >>, >, >=, <=>, ===, [], []=, []?, [, &+, &-, &*, &** (not 'NEWLINE')
```

I'm using:

* VS Code version: 1.40.2.
* Crystal 0.31.1 (2019-10-02)
* vscode-crystal-lang: 0.3.11

Thanks!

**Comment by ndbroadbent** [comment]
I found this PR that fixes the issue: https://github.com/crystal-lang-tools/vscode-crystal-lang/pull/99

Hopefully this can be merged soon!

**Comment by ndbroadbent** [comment]
Duplicate of: https://github.com/crystal-lang-tools/vscode-crystal-lang/issues/84
